---
name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: [self-hosted, runner, mgmt, base]
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label, comment on PR or this will be closed in 10 days.'
          days-before-stale: 30
          days-before-close: 10
